### ISSUE TITLE
Meriwest Credit Union Essay Contest

### ISSUE THREAD

**Issue by freedomfry** [jonahweissman/jonah-college#13]
https://www.meriwest.com/rcfs/yourpdfs/marketing/essay-competition-entry-release-form.pdf

**Comment by freedomfry** [comment]
Needs the following:

Please **submit verification** of Grade Point Average (GPA) and grade level – along with this entry form and your essay

**Comment by freedomfry** [comment]
1. Prepare a 1,000-word essay discussing the following: The credit union philosophy is “People Helping People”. What could credit unions do to make this philosophy relevant to students.
2. Send us a copy of your transcript verifying your GPA & grade level.
3. Complete this form. (Meriwest membership required.)
4. Submit all required forms to any Meriwest Credit Union financial center, or scan and email in .pdf format to jpopolizio@meriwest.com, or mail them to:
  Meriwest Credit Union
  Attn: Jill Popolizio
  5615 Chesbro Avenue
  San Jose, CA 95123

**Comment by jonahweissman** [comment]
submitted, got rejected
