### ISSUE TITLE
Jefferson Scholars

### ISSUE THREAD

**Issue by jonahweissman** [jonahweissman/jonah-college#6]
- [x] [Activities](../tree/master/UVA/jefferson-scholars/activities.md)
- [x] [Awards](../tree/master/UVA/jefferson-scholars/awards.md)
- [x] [Leadership Essay](../tree/master/UVA/jefferson-scholars/leadership.md)
- [x] [Personal Essay](../tree/master/UVA/jefferson-scholars/personal.md)
- [x] Submission

**Comment by jonahweissman** [comment]
@JuliaRubarth I went over everything with Dad. Could you take a look before I submit?

**Comment by JuliaRubarth** [comment]
Ok. I'll look at it now

**Comment by jonahweissman** [comment]
Submitted
