### ISSUE TITLE
College lists

### ISSUE THREAD

**Issue by jonahweissman** [jonahweissman/jonah-college#8]
2018 Best Colleges for Computer Science in America
https://www.niche.com/colleges/search/best-colleges-for-computer-science/

1. Massachusetts Institute of Technology
2. Stanford University
3. Carnegie Mellon University
4. Harvard University
5. California Institute of Technology
6. Yale University
7. Rice University
8. Georgia Institute of Technology
9. University of Southern California
10. University of Pennsylvania
11. Vanderbilt University
12. Brown University
13. Columbia University
14. University of California - Berkeley
15. Harvey Mudd College
16. Dartmouth College
17. University of Illinois at Urbana-Champaign
18. Cornell University
19. University of Chicago
20. University of Michigan - Ann Arbor
21. University of California - Los Angeles
22. Washington University in St. Louis
23. Duke University
24. Rensselaer Polytechnic Institute
25. University of Texas - Austin

 
 
25 Best Artificial Intelligence Colleges
https://successfulstudent.org/best-artificial-intelligence-colleges/

1. Carnegie Mellon University (Pittsburgh, PA)
2. Stanford University (Stanford, CA)
3. Massachusetts Institute of Technology (Cambridge, MA)
4. University of California, Berkeley (Berkeley, CA)
5. Harvard University (Cambridge, MA)
6. Yale University (New Haven, CT)
7. Cornell University (Ithaca, NY)
8. University of Maryland (College Park, MD)
9. Columbia University (New York City, NY)
10. University of Texas (Austin, TX)
11. University of California, Los Angeles (Los Angeles, CA)
12. University of Michigan (Ann Arbor, MI)
13. Georgia Institute of Technology (Atlanta, GA)
14. University of Massachusetts (Amherst, MA)
15. University of Illinois (Urbana/Champaign, IL)
16. University of Pennsylvania (Philadelphia, PA)
17. University of Southern California (Los Angeles, CA)
18. California Institute of Technology (Pasadena, CA)
19. University of Wisconsin (Madison, WI)
20. University of Georgia (Athens, GA)
21. University of Washington (Seattle, WA)
22. Colorado State University (Fort Collins, CO)
23. University of Pittsburgh (Pittsburgh, PA)
24. South Dakota School of Mines and Technology (Rapid City, SD)
25. Eastern Michigan University (Ypsilanti, MI)

Top 20 Artificial Intelligence Engineering Schools in the U.S. 2016
http://www.computersciencedegreehub.com/best/artificial-intelligence-engineering-schools/

1. University of California San Diego
2. Georgia State University
3. Purdue University
4. Columbia University New York
5. Rensselaer Polytechnic Institute
6. Harvard University
7. Ohio State University
8. University of Rochester
9. Northwestern University
10. Oregon State University
11. Indiana University
12. University of Massachusetts Amherst
13. University of Illinois Urbana Champaign
14. University of Michigan
15. University of California Berkeley
16. University of Pennsylvania
17. University of Georgia
18. Stanford University
19. University of Washington
20. University of Tennessee Knoxville

 
Ivy League Schools – consider at least 2. These wealthy schools often have the largest scholarships.

1. Brown University
2. Columbia University
3. Cornell University
4. Dartmouth College
5. Harvard University
6. Princeton University
7. University of Pennsylvania
8. Yale University

**Comment by JuliaRubarth** [comment]
How can I help narrow these lists of schools to ones that appeal to you?

**Comment by jonahweissman** [comment]
I'm not really sure how to use these lists either

**Comment by JuliaRubarth** [comment]
Could you start with the list that most closely appeals to you then start
at the top and pluck off colleges based on definite nos and possible yeses
then check out websites or discussion boards?



<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by freedomfry** [comment]
I sorted them by rank and noted three schools that appear more than 1 time in the combined top 10: Columbia, Harvard, and Yale.
[College Choices.xlsx](https://github.com/jonahweissman/jonah-college/files/1525138/College.Choices.xlsx)

**Comment by JuliaRubarth** [comment]
Ok. Let me know how I can be helpful with the next steps.

**Comment by jonahweissman** [comment]
done with this
